# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
